In [19]:
import numpy as np
import scipy as sp
from scipy import spatial
import time

In [2]:
X = np.array([[1,2],[2,3],[3,4]])
X

array([[1, 2],
       [2, 3],
       [3, 4]])

In [14]:
y = np.array([[1,3]])
np.amin(spatial.distance_matrix(X, y))

1.0

In [26]:
X = np.random.rand(90000,2)*500

In [27]:
stime = time.time()
for _ in range(1000):
    y = np.random.rand(1,2)*500
    #print(f'y value is: {y}')
    distances = spatial.distance_matrix(X,y)
    print(f'minimum distance is: {np.amin(distances)}')
    print(f'it occurs at: {np.where(distances==np.amin(distances))}')
    print(f'that point is: {X[np.where(distances==np.amin(distances))[0]]}')
    print('---------------------')
etime = time.time()
print(f'that took: {etime - stime} seconds')

minimum distance is: 0.5054242251408334
it occurs at: (array([15088]), array([0]))
that point is: [[105.4907272   27.95326328]]
---------------------
minimum distance is: 0.3170788287408888
it occurs at: (array([89013]), array([0]))
that point is: [[241.76074887 195.04388014]]
---------------------
minimum distance is: 0.4465225997047885
it occurs at: (array([14878]), array([0]))
that point is: [[425.44847285 213.63697158]]
---------------------
minimum distance is: 0.6163124278695893
it occurs at: (array([45215]), array([0]))
that point is: [[ 21.47514574 174.04997144]]
---------------------
minimum distance is: 1.4634832733885905
it occurs at: (array([31700]), array([0]))
that point is: [[162.85855038 402.01467151]]
---------------------
minimum distance is: 0.31861513101390265
it occurs at: (array([10625]), array([0]))
that point is: [[104.24054751 133.42792263]]
---------------------
minimum distance is: 0.4604239937953256
it occurs at: (array([72147]), array([0]))
that point is: [

That finds the value for k=1 but I think I can find the higher values of k with a single function. 

np.argpartition shows potential in my research

In [97]:
class KNearestNeighbors():
    def __init__(self, neighbors):
        self.neighbors = neighbors

    def fit(self, data):
        self.data = data

    def predict(self, y):
        dist = spatial.distance_matrix(self.data, y)
        kmin_index = np.argsort(dist, axis=0)
        return self.data[kmin_index[:self.neighbors]], dist[kmin_index[:self.neighbors]]

In [98]:
X = np.random.rand(9000,2)*1000
y = np.random.rand(1,2) *1000
X

array([[205.36782006, 176.23155393],
       [532.58148178, 615.13538344],
       [222.98193081, 214.9521709 ],
       ...,
       [601.86684435,   9.49585089],
       [903.58320214, 376.73966798],
       [355.10910315, 225.25087104]])

In [100]:
neigh = KNearestNeighbors(5)
neigh.fit(X)
neigh.predict(y)

(array([[[735.74334991, 953.45999191]],
 
        [[737.8345872 , 945.1824409 ]],
 
        [[731.8544263 , 946.36331095]],
 
        [[749.10422931, 954.46852802]],
 
        [[727.55630453, 955.13422666]]]), array([[[ 3.00441757]],
 
        [[ 6.7128051 ]],
 
        [[ 8.48223992]],
 
        [[11.11184648]],
 
        [[11.2243095 ]]]))

In [101]:
np.__version__

'1.18.1'

In [81]:
dist = spatial.distance_matrix(X, y)
np.argsort(dist, axis=0)

array([[1],
       [0],
       [2],
       [3],
       [4]])

In [82]:
dist

array([[ 6.12922063],
       [ 4.69958538],
       [ 6.67954545],
       [ 7.42384527],
       [10.10401961]])